# This is a basic workflow to help you get started with Actions

name: WakaTime Stat Update

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  schedule:
    # Runs every hour
    - cron: '0 * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
# The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
          
      - name: WakaTime Stat Update Action
        # You may pin to the exact commit or the version.
        # uses: avinal/Profile-Readme-WakaTime@f0032b5824f6358a14bb8f947ed18488621fd222
        uses: avinal/Profile-Readme-WakaTime@v2.5
        with:
          # Your WakaTime API Key
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          # GitHub access token
          GITHUB_TOKEN: ${{ github.token }}
          # Which branch is used for saving images
          BRANCH: "master"
          # Manual commit messages
          COMMIT_MSG: "Automated Coding Activity Update :alien:"
